//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultDatabaseClass6
    {
        public long StudentId { get; set; }
        public string Term { get; set; }
        public Nullable<int> Bengali1st { get; set; }
        public Nullable<int> English1st { get; set; }
        public Nullable<int> Mathematics { get; set; }
        public Nullable<int> Science { get; set; }
        public Nullable<int> Bangladesh_and_Global_Studies { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> Drawing { get; set; }
        public Nullable<int> Physical_Education { get; set; }
        public Nullable<int> ICT { get; set; }
        public Nullable<int> Bengali2nd { get; set; }
        public Nullable<int> English2nd { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<double> Gpa { get; set; }
        public Nullable<int> TotalSubject { get; set; }
    }
}
