//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultDatabaseClass5
    {
        public long StudentId { get; set; }
        public string Term { get; set; }
        public Nullable<int> Bengali { get; set; }
        public Nullable<int> English { get; set; }
        public Nullable<int> Mathematics { get; set; }
        public Nullable<int> Bangladesh_and_Global_Studies { get; set; }
        public Nullable<int> Science { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public double Gpa { get; set; }
        public Nullable<int> TotalSubject { get; set; }

    }
}
